### ISSUE TITLE
After installing the plugin getting UNEXPECTED TOP-LEVEL EXCEPTION when building for android

### ISSUE THREAD

**Issue by pmwisdom** [raix/push#116]
https://github.com/phonegap-build/PushPlugin/issues/583

Seems to be the same one as this. I believe in my situation its a conflict between Push and Cordova Google Maps.

Any Advice?

**Comment by pmwisdom** [comment]
This is the actual message.

* What went wrong:
   Execution failed for task ':dexDebug'.
   > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
   /Users/Paul/adt-bundle-mac-x86_64-20140702/sdk/build-tools/21.0.0/dx --dex --no-optimize --output
   /Development/flybuy/meteor-app/.meteor/local/cordova-build/platforms/android/build/intermediates/dex/debug
   --input-list=/Development/flybuy/meteor-app/.meteor/local/cordova-build/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
   Error Code:
   2
   Output:
   
   UNEXPECTED TOP-LEVEL EXCEPTION:
   com.android.dex.DexException: Multiple dex files define Landroid/support/v4/view/PagerAdapter;
   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
   at com.android.dx.command.dexer.Main.run(Main.java:245)
   at com.android.dx.command.dexer.Main.main(Main.java:214)
   at com.android.dx.command.Main.main(Main.java:106)

**Comment by pmwisdom** [comment]
I found out what the problem was. Its a dependency issue between using that android-support dependency and the play services framework. The main cordova push plugin does it the framework way. I see that your working on weeding out that deprecated plugin with the new re write so I'm guessing this will be taken care of then. Close this if that turns out to be true. Cheers.

**Comment by raix** [comment]
Please try `raix:push@3.0.0-rc.2`

**Comment by pmwisdom** [comment]
Perfect this is solved in push@3.0.0.
