### ISSUE TITLE
cordova.plugin.local-notification error in Android build

### ISSUE THREAD

**Issue by mikepaszkiewicz** [raix/push#117]
Thinking this has something to do with 1.2 changes...did a simple meteor-build command that resulted in this:
```
% WARNING: org.apache.cordova.device has been renamed to cordova-plugin-device. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.device` and `cordova plugin add cordova-plugin-device`.
% Fetching plugin "org.apache.cordova.device" via cordova plugins registry
% Failed to install 'de.appplant.cordova.plugin.local-notification':CordovaError: Failed to fetch plugin org.apache.cordova.device via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
undefined
  at registry.fetch.fail.then.pinfo (/Users/michaelpaszkiewicz/.meteor/packages/meteor-tool/.1.1.8.1cmnfyj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:141:33)
  at _rejected (/Users/michaelpaszkiewicz/.meteor/packages/meteor-tool/.1.1.8.1cmnfyj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:797:24)
  at /Users/michaelpaszkiewicz/.meteor/packages/meteor-tool/.1.1.8.1cmnfyj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:823:30
  at Promise.when (/Users/michaelpaszkiewicz/.meteor/packages/meteor-tool/.1.1.8.1cmnfyj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:1035:31)
  at Promise.promise.promiseDispatch (/Users/michaelpaszkiewicz/.meteor/packages/meteor-tool/.1.1.8.1cmnfyj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:741:41)
  at /Users/michaelpaszkiewicz/.meteor/packages/meteor-tool/.1.1.8.1cmnfyj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:557:44
  at flush (/Users/michaelpaszkiewicz/.meteor/packages/meteor-tool/.1.1.8.1cmnfyj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:448:13)

=> Errors executing Cordova commands:

   While adding platform Android to Cordova project:
   Cordova error: CordovaError: Failed to fetch plugin org.apache.cordova.device via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
   Check your connection and plugin name/version/URL.
   undefined
   at registry.fetch.fail.then.pinfo
```

**Comment by raix** [comment]
https://github.com/raix/push/tree/es2015/meteor1.2/cordova5

**Comment by raix** [comment]
Please try `raix:push@3.0.0-rc.2`
