### ISSUE TITLE
pem files get "unknow asset" error

### ISSUE THREAD

**Issue by occasl** [raix/push#119]
When trying to launch my project on an ios-device, my project errors out with the following:

```
W20150925-16:55:45.792(-7)? (STDERR)
W20150925-16:55:45.794(-7)? (STDERR) /Users/lsacco/.meteor/packages/meteor-tool/.1.1.8.19nxnpc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150925-16:55:45.794(-7)? (STDERR)            				throw(ex);
W20150925-16:55:45.794(-7)? (STDERR)            				      ^
W20150925-16:55:45.797(-7)? (STDERR) Error: Unknown asset: apn/key-ma-approvals.pem
W20150925-16:55:45.797(-7)? (STDERR)     at Object.Future.wait (/Users/lsacco/.meteor/packages/meteor-tool/.1.1.8.19nxnpc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
W20150925-16:55:45.797(-7)? (STDERR)     at getAsset (/Users/lsacco/dev/mobile-approvals/approvalhub/.meteor/local/build/programs/server/boot.js:212:20)
W20150925-16:55:45.797(-7)? (STDERR)     at Object.Assets.getText (/Users/lsacco/dev/mobile-approvals/approvalhub/.meteor/local/build/programs/server/boot.js:217:16)
W20150925-16:55:45.798(-7)? (STDERR)     at push.config.os.js:4:1
W20150925-16:55:45.798(-7)? (STDERR)     at /Users/lsacco/dev/mobile-approvals/approvalhub/.meteor/local/build/programs/server/boot.js:249:5
W20150925-16:55:45.798(-7)? (STDERR)     - - - - -
W20150925-16:55:45.798(-7)? (STDERR)     at getAsset (/Users/lsacco/dev/mobile-approvals/approvalhub/.meteor/local/build/programs/server/boot.js:206:19)
W20150925-16:55:45.798(-7)? (STDERR)     at Object.Assets.getText (/Users/lsacco/dev/mobile-approvals/approvalhub/.meteor/local/build/programs/server/boot.js:217:16)
W20150925-16:55:45.798(-7)? (STDERR)     at push.config.os.js:4:1
W20150925-16:55:45.798(-7)? (STDERR)     at /Users/lsacco/dev/mobile-approvals/approvalhub/.meteor/local/build/programs/server/boot.js:249:5
```

Here's the command I'm using:
```
➜  approvalhub git:(feature/raix-push) ✗ meteor run ios-device --mobile-server ma-meteor-demo.xxx.com --production
```

Here's my config.push.json:

```
{
  "apn": {
    "passphrase": "xxxxx",
    "key": "apn/key-ma-approvals-prod.pem",
    "cert": "apn/cert-ma-approvals-prod.pem"
  },
  "apn-dev": {
    "passphrase": "xxxxx",
    "key": "apn/key-ma-approvals.pem",
    "cert": "apn/cert-ma-approvals.pem"
  },
  "gcm": {
    "apiKey": "xxxx",
    "projectNumber": "xxxx"
  },
  "production": false,
  "badge": true,
  "sound": true,
  "alert": true,
  "vibrate": true,
  "sendInterval": 15000
}
```

**Comment by occasl** [comment]
As it turns out, I just needed to move my "apn/" directory under a "private/" directory but not change the directory for the key/cert location in config.push.json.
