### ISSUE TITLE
Cordova fails

### ISSUE THREAD

**Issue by dnish** [raix/push#128]
Hello,
when adding your package, I get the following error on build:

    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

    FAILURE: Build failed with an exception.

It has something to do with phonegap-plugin-push. I got the same error when I only add that Cordova plugin to my project. I'm using Meteor 1.2

**Comment by raix** [comment]
Are you using push 3.x?

**Comment by dnish** [comment]
Hi,
yeah, I've used 3.0.0. Think it has something to do with https://github.com/phonegap/phonegap-plugin-push/issues/199

**Comment by kimeshan-gleat** [comment]
Are you also using the cordova facebook pugin? Because Cordova facebook uses android support v4 while phonegap push uses v13 and this causes that DexException.

**Comment by dnish** [comment]
@kimeshan-gleat Nope, I'm using some other plugins like Local Notification. I know that my Meteor app loads "android-support-v4" while building the app, I'll later check which plugin causes the the issue. Thank you for the information.

**Comment by kimeshan-gleat** [comment]
@dnish this might help: http://stackoverflow.com/questions/21102598/android-studio-unexpected-top-level-exception

**Comment by dnish** [comment]
In my case, I've removed https://github.com/katzer/cordova-plugin-local-notifications - is there a way to fire local notification with the "raix:push" plugin? I'm using GCM only when the user is offline and want to fire a notification without GCM when he is online.
