### ISSUE TITLE
Socket Issue

### ISSUE THREAD

**Issue by jpgilchrist** [raix/push#131]
After updating from 2.6.x to 3.0.1, I received the following error:

Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment
    at Connection.connect.delay.then.fail.delay (/mnt/app/programs/server/npm/raix_push/node_modules/apn/lib/connection.js:224:10)
    at _fulfilled (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:796:13)
    at /mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:448:13)

This is resulting in the server restarting.

**Comment by jpgilchrist** [comment]
On second thought, the server restart issue is most likely a Modulus error with an update from one of the meteor packages. But the "Socket unusable after connection" issue still remains.

**Comment by jpgilchrist** [comment]
This is really just a Modulus problem.
