### ISSUE TITLE
Error: Socket unusable after connection.

### ISSUE THREAD

**Issue by jpgilchrist** [raix/push#133]
This is the output in my logs. 

1. Push.debug = true, production = false
2. Verified both prod and dev certs through openssl commands (locally and on remote server)
3. I'm deploying to a Digital Ocean server with meteor up.

I really need some assistance on this. 

```
Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment 
at Connection.connect.delay.then.fail.delay (/opt/burn/app/programs/server/npm/raix_push/node_modules/apn/lib/connection.js:224:10) 
at _fulfilled (/opt/burn/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:834:54) 
at self.promiseDispatch.done (/opt/burn/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:863:30) 
at Promise.promise.promiseDispatch (/opt/burn/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:796:13) 
at /opt/burn/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:604:44 
at runSingle (/opt/burn/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:137:13) 
at flush (/opt/burn/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:125:13)
at process._tickCallback (node.js:448:13) 
error: Forever detected script exited with code: 7
error: Script restart attempt #7
```

**Comment by jpgilchrist** [comment]
I dug into the error at raix_push/node_modules/apn/lib/connection.js:224:10 and found that it was conditionally using the certs based on the environment variable NODE_ENV. I explicitly set NODE_ENV to development and voila. It works.

**Comment by raix** [comment]
@jpgilchrist maybe we should have the push package write a warning message in the  log?

**Comment by jpgilchrist** [comment]
Yes. I would think it would make sense to check the NODE_ENV environment variable at the same time the following message is logged: 

(STDERR) WARNING: Push APN is using development key and certificate

Including a warning if there's a mismatch between development versus production.
