### ISSUE TITLE
Error on app deployed to meteor.com

### ISSUE THREAD

**Issue by LucNaterop** [raix/push#135]
When I run my app with a local server, push notifications work fine. However, if I deploy the app to meteor.com I get the following client error: 

```javascript
XMLHttpRequest cannot load https://ddp--9894-tauschhandel.meteor.com/sockjs/info?cb=wracexxzw0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://tauschhandel.meteor.com' is therefore not allowed access. The response had HTTP status code 503.
77a3bc59746698835930bf83e839ba1545901602.js?meteor_js_resource=true:73 GET https://ddp--8029-tauschhandel.meteor.com/sockjs/info?cb=ue45vwz_pn y._start @ 77a3bc59746698835930bf83e839ba1545901602.js?meteor_js_resource=true:73(anonymous function) @ 77a3bc59746698835930bf83e839ba1545901602.js?meteor_js_resource=true:73
```

The same error comes up when I deploy my app to Modulus. Strange. Here's the error shown on the server: 
```javascript

Push: Sent message "Roter Stift" to 1 ios apps 0 android apps

Push, GUIDE: The "Push.appCollection" - No GCM clients have registred on the server yet...



/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:155

                throw e;
 
 
 
 
^

Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment
    at Connection.connect.delay.then.fail.delay (/mnt/app/programs/server/npm/raix_push/node_modules/apn/lib/connection.js:224:10)
    at _fulfilled (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:796:13)
    at /mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/mnt/app/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:448:13)

```

Even on Digital Ocean, I get the same error. Could it be that the ports are not open? Here's the output of "ufw status":

```javascript
To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
22/tcp                     ALLOW       Anywhere
80                         ALLOW       Anywhere
5223/tcp                   ALLOW       Anywhere
2195/tcp                   ALLOW       Anywhere
2196/tcp                   ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
```

Any ideas on which hosting service to use with raix:push?

**Comment by insaneinc01** [comment]
Same issue on Modulus.io. 
But this issue started after upgrading raix:push to 3.0.1. With an older version it was working fine. 
Not sure if its also linked to Meteor 1.2 upgrade. 
Please help! Thanks

**Comment by jpgilchrist** [comment]
@insaneinc01 @LucNaterop you need to make sure your NODE_ENV environment variable is also set and it should correspond to the production attribute on your push config file. If production is false then NODE_ENV should be set to "development"; if production is true then NODE_ENV should be set to true.

**Comment by LucNaterop** [comment]
Absolutely, that did the trick. Thank you, kind sir!
