### ISSUE TITLE
Push notifications stopped

### ISSUE THREAD

**Issue by adamgins** [raix/push#140]
Hi, Push has been working well for ages. For some reason I stopped receiving notification on my phone (which I do install/uninstall test with various versions (dev) from time to time. 

Anyway, I had just reinstalled from production and I am not getting push notifications. From what I understand he register does not seem to be working. I cleared out `_raix_push_app_tokens` for my ID as there were about 30 entries in there now and I can't see any records in there (even after installing/re-installing a few time). 

Other users are still getting notifications.

Not sure if this is related to https://github.com/raix/push/issues/139

Any ideas, pls?

**Comment by pmwisdom** [comment]
I'm not sure if 3.0.1 was the version, but the cordova plugin this is based upon was changed to the new one, which might require a new app store submission to work properly.

**Comment by adamgins** [comment]
@pmwisdom you're probably spot on. Bad me did not check for plugin changes. 

That said, do you have any ideas on best way to integrate this without alienating current users. Ie we can force them to upgrade the app, right? Is there a way to fall back to another plugin, if they don't have it?

@raix wondering if you have any ideas/comments, too, please?

**Comment by dennisharrison** [comment]
@adamgins We're deploying each 'version' pushed through the app store to a different hostname (cav123.yourapphostname.tld, cav124.yourapphostname.tld, etc) and snatching that string to determine whether to do A or B or C on server side.  Another more simple approach would be to deploy the app again at another URL altogether.

Hope that helps?

**Comment by pmwisdom** [comment]
@adamgins 

Well, you cant "force" them to upgrade, but you **could** install https://www.npmjs.com/package/cordova-plugin-appversion. Check their binary version and float a popup if they don't have the most recent when they open the app to upgrade. I think Apple frowns upon that though.

**Comment by raix** [comment]
@adamgins We could create a legacy version adding parts of the old client.cordova code - but a message to the user about upgrading their app might be the easiest / cleanest solution.

**Comment by ernestorocha** [comment]
3.0.2 it's not working for me. At least on android.

Downgraded to 3.0.1 and now it's working. I updated the APK and deployed the server, so I don't know where the problem can be. But, I have this on the server:

```
WARNING: Push APN is in development mode
```

This message wasn't not showing on 3.0.2, and I only have the production config.

**Comment by adamgins** [comment]
@pmwisdom thanks. Mmm could be large impact as we currently use a single url no matter what device type you're using and people can use cordova or web... so would have to do a bunch of redirection/checking ... definitely can be done but a fair bit of work.

@raix I have been lazy and left Buzzy using Push 2.6.12

I just noticed this error on the logs:
```
2015-12-11 09:52:22+11:00Exception while invoking method 'raix:push-setuser' Error: Match error: Expected string, got object
shzz
2015-12-11 09:52:22+11:00Sanitized and reported to the client as: Match failed [400]
shzz
2015-12-11 09:52:22+11:00
shzz
2015-12-11 09:52:22+11:00 at check (packages/check/match.js:33:1)
shzz
2015-12-11 09:52:22+11:00 at [object Object].Meteor.methods.raix:push-setuser (packages/raix_push/packages/raix_push.js:822:1)
shzz
2015-12-11 09:52:22+11:00 at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
shzz
2015-12-11 09:52:22+11:00 at maybeAuditArgumentChecks (livedata_server.js:1698:12)
shzz
2015-12-11 09:52:22+11:00 at livedata_server.js:708:19
shzz
2015-12-11 09:52:22+11:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
shzz
2015-12-11 09:52:22+11:00 at livedata_server.js:706:40
shzz
2015-12-11 09:52:22+11:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
shzz
2015-12-11 09:52:22+11:00 at livedata_server.js:704:46
shzz
2015-12-11 09:52:22+11:00 at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
```

Just wondering if this is a fixed in later versions and if so a way to retrofit into a 2.6 steam, pls?

**Comment by adamgins** [comment]
@raix sorry to hassle - any thoughts on the error above in a legacy raix:push version, pls? 
Just have production users not getting messages.

**Comment by raix** [comment]
@adamgins I'm wondering why the user id is an object (objectId on the client?)

**Comment by adamgins** [comment]
yep, not sure… I started looking into today but hard to trace. I can start putting in some additional debug statements. I have debug set to true.. .but have not tracked down the issue.

Adam Ginsburg
adam.ginsburg@buzzy.buzz
tel: +61 411 151 732
https://buzzy.buzz

**Comment by adamgins** [comment]
@raix I put a console.log on what I am passing to push send: It looked OK to me .. any ideas pls?

```
Push: Got push token from app: { id:
hqaq
2015-12-18 16:28:18+11:00 { _id: '<long id>',
hqaq
2015-12-18 16:28:18+11:00 createdAt: '2015-01-02T21:09:18.888Z',
hqaq
2015-12-18 16:28:18+11:00 updatedAt: '2015-10-10T05:07:53.900Z',
hqaq
2015-12-18 16:28:18+11:00 token: { apn: '<long apn>' },
hqaq
2015-12-18 16:28:18+11:00 appName: 'main',
hqaq
2015-12-18 16:28:18+11:00 userId: '<long id>' },
hqaq
2015-12-18 16:28:18+11:00 token: { apn: '<long apn>' },
hqaq
2015-12-18 16:28:18+11:00 appName: 'main',
hqaq
2015-12-18 16:28:18+11:00 userId: '<long id>',
hqaq
2015-12-18 16:28:18+11:00 metadata: {} }
hqaq
2015-12-18 16:28:18+11:00Sanitized and reported to the client as: Match failed [400]
hqaq
2015-12-18 16:28:18+11:00
hqaq
2015-12-18 16:28:18+11:00Exception while invoking method 'raix:push-setuser' Error: Match error: Expected string, got object
hqaq
2015-12-18 16:28:18+11:00 at check (packages/check/match.js:33:1)
hqaq
2015-12-18 16:28:18+11:00 at [object Object].Meteor.methods.raix:push-setuser (packages/raix_push/packages/raix_push.js:822:1)
hqaq
2015-12-18 16:28:18+11:00 at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
hqaq
2015-12-18 16:28:18+11:00 at maybeAuditArgumentChecks (livedata_server.js:1698:12)
hqaq
2015-12-18 16:28:18+11:00 at livedata_server.js:708:19
hqaq
2015-12-18 16:28:18+11:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
hqaq
2015-12-18 16:28:18+11:00 at livedata_server.js:706:40
hqaq
2015-12-18 16:28:18+11:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
hqaq
2015-12-18 16:28:18+11:00 at livedata_server.js:704:46
hqaq
2015-12-18 16:28:18+11:00 at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
hqaq
2015-12-18 16:28:18+11:00Exception while invoking method 'raix:push-update' Error: Match error: Expected string, got object in field id
hqaq
2015-12-18 16:28:18+11:00 at check (packages/check/match.js:33:1)
hqaq
2015-12-18 16:28:18+11:00 at [object Object].Meteor.methods.raix:push-update (packages/raix_push/packages/raix_push.js:747:1)
hqaq
2015-12-18 16:28:18+11:00 at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
hqaq
2015-12-18 16:28:18+11:00 at maybeAuditArgumentChecks (livedata_server.js:1698:12)
hqaq
2015-12-18 16:28:18+11:00 at livedata_server.js:708:19
hqaq
2015-12-18 16:28:18+11:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
hqaq
2015-12-18 16:28:18+11:00 at livedata_server.js:706:40
hqaq
2015-12-18 16:28:18+11:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
hqaq
2015-12-18 16:28:18+11:00 at livedata_server.js:704:46
hqaq
2015-12-18 16:28:18+11:00 at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
hqaq
2015-12-18 16:28:18+11:00Sanitized and reported to the client as: Match failed [400]
hqaq
2015-12-18 16:28:18+11:00
```

**Comment by adamgins** [comment]
@raix, I did check onf the users who seem to have the follow doc in `_raix_push_app_tokens` 

```
{
  _id: "<some id>",
  appName: "main",
  userId: "<some user id>",
  createdAt: ISODate("2015-07-22T06:39:06.784Z"),
  updatedAt: ISODate("2015-10-20T05:09:04.732Z")
}
```

Could it be that there is no `token` in that document?

BTW, I am not 100% sure this is the record that is causing the error as the logs are convoluted with a bunch of stuff.

**Comment by adamgins** [comment]
I also noticed some docs where `userId: null`, wondering if these would cause an issue too?

**Comment by adamgins** [comment]
@raix is it possible to get a fork of the v 2.6.12 branch please, so I can try debug this issue? I can't seem to see it  in the repo.

**Comment by MoeBadr** [comment]
@adamgins I having the same issue, Have you resolved it ?. 
currently the `user:null`, I've attempted your solution but I'm still having the same issue of userId being `null`

**Comment by adamgins** [comment]
@MoeBadr sorrry I have not solved this. @raix how do I get the old branch, pls?

**Comment by MoeBadr** [comment]
@adamgins 

Client Side 

```javascript 
if(Session.get('pushToken')!== undefined && Meteor.userId()){
    Push.setUser(Session.get('pushToken'));
}
```
Just attempted this solution & it works for me, since whenever `userId()` is changed this code runs.

**Comment by MoeBadr** [comment]
@adamgins seems like `userId` is still getting set to `null` only for apn tokens. @raix any ideas what might be the problem ?

**Comment by MoeBadr** [comment]
@raix I haven't been able to resolve the issue of some docs having `userId` as `null`, any advice of what might be causing the issue ?

**Comment by raix** [comment]
hmm, I wonder - let me check up on this - could be that expected type if string but null is an object, should be valid enough though

**Comment by adamgins** [comment]
@raix moving back to this thread as https://github.com/raix/push/issues/127 was Android specific and my issues is happening on iOS. 

I am really struggling with getting this running with Meteor 1.3. I have 2.6.12 running OK with Meteor 1.2 and it's been running fine for ages (Thanks!!!). push 2.6.12 won't install on Meteor 1.3 as I think it requires iOS 7 and Meteor 1.3 requires iOS 8+ and I think the pushplugin won't run with that version of Cordova??

Anyway, I created a vanilla raix:push 3.0.2 with Meteor 1.3 app here https://github.com/Buzzy-Buzz/pushtest for some reason it never gets the token (this alert never shows: https://github.com/Buzzy-Buzz/pushtest/blob/master/client/push.js#L9 ). It seems to register OK, eg I see the following in XCode console (via Physical phone): 

```
2016-04-06 13:46:29.590 Push Test[668:253822] Push Plugin register success: <some long string>
2016-04-06 13:46:30.455 Push Test[668:253822] active

```

to set the sample above up you'd need to:

1. add your certificates as per config
2.  create a user you can hard code the ID and password as per https://github.com/Buzzy-Buzz/pushtest/blob/master/client/main.js#L9 sorry I had issues with {{> loginButtons}} not showing on Cordova, so I just hardcoded the ID and password as I did not want to wast time getting that working. You should be able to create the user via desktop browser. 

Any help appreciated. Hoping I can get this sorted :-)

**Comment by raix** [comment]
hmm - so It breaks in 1.3 - I'm guessing that it might be related to the cordova update, got to find some time to look into it.

**Comment by adamgins** [comment]
@raix  thanks. That said it seems like it was broken before that for me... or at least the symptoms seemed similar to the start of this thread. 

I ended up cloning and trying to change some of the version numbers on the push, APN and GCM packages you were including,  but I got a ton of errors and thought I should check in back with you.

**Comment by raix** [comment]
@adamgins are you using the `json` config or `Push.Configure`? *(we are only using the `Push.Configure` - so it could be an issue with the `json` config reader - might want to deprecate it)*

**Comment by adamgins** [comment]
I am using JSON config. I thought Push.Configure was already deprecated. See the repo I replicated the error in https://github.com/Buzzy-Buzz/pushtest/blob/master/config.push.json

**Comment by raix** [comment]
not really - we use Push.Configure - we might want to remove the json config stuff. The reason is to simplify usage and the code base. (less to QA)

@adamgins try using the `Push.Configure` instead,

**Comment by adamgins** [comment]
@raix thanks

ok it was the "Outdated" statement https://github.com/raix/push/blob/v3.x/docs/ADVANCED.md#note-outdated that threw me off:

Do I need to run on client too?

if I run:

```
Push.Configure({
    "apn": {
        "passphrase": "<pass>",
        "key": Assets.getText('Prod_BuzzyBuzzKey.pem'),
        "cert": Assets.getText('Prod_BuzzyBuzzCert.pem')
    },
    "apn-dev": {
        "passphrase": "<pass>",
        "key": Assets.getText('Dev_PushChatKey.pem'),
        "cert": Assets.getText('Dev_PushChatCert.pem')
    },
    "gcm": {
        "apiKey": "<key>,
        "projectNumber": <num>
    },
    "production": true,
    "badge": false,
    "sound": true,
    "alert": true,
    "vibrate": true
})
```
on the server console I see:
```
I20160408-12:24:36.379(10)? Push.Configure { apn: 
I20160408-12:24:36.381(10)?    { passphrase: '<pass>',
I20160408-12:24:36.382(10)?      key: 'Bag Attributes\n    friendlyName: BuzzyBuzz\n    localKeyID: <hex numbers> \nKey Attributes: <No Attributes>\n-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: <long strong>
```
Then further down I see:

```
I20160408-12:13:36.222(10)? Push: APN configured
W20160408-12:13:36.222(10)? (STDERR) WARNING: Push APN is configured to production mode - but server is running from localhost
W20160408-12:13:36.222(10)? (STDERR) ERROR: Push server could not find certData
W20160408-12:13:36.222(10)? (STDERR) ERROR: Push server could not find keyData
I20160408-12:13:36.288(10)? GCM configured
```
So it looks like it's getting the certData and then the keyData but still gets an error. 

Any ideas pls?

**Comment by adamgins** [comment]
Thanks @raix 
I was a bit confused by the 'outdated' mentioned here https://github.com/raix/push/blob/v3.x/docs/ADVANCED.md#note-outdated

I just tried with `Push.Configure` on the server. I still seem to have the same issue. Ie it never gets a token.  Do I need to run it `Push.Configure` on the client too? I don't currently do this with v2.6.12

What causes the listener to get a token after the user logs in? I I don't think the autorun here https://github.com/raix/push/blob/90d7ce94a37d6b25e45dcfda9f45769851b053c8/lib/client/client.js#L163 is ever invoked after the user logs in.

I checked the local storage and could not see `_raix:push_token`

so I am guessing this is where the issue is, any ideas on how I solve. I tried call `Push.setUser()` although not sure how I am meant to be calling it?

Any ideas welcome

**Comment by raix** [comment]
yes both the client and the server need Push.Configure for it to work, (this should be on the latest version of push)

**Comment by adamgins** [comment]
yep, I am running this in raix:push 3.0.2 

I am now call `Push.Configure ` on the client too. I see this in the Xcode console:

```
2016-04-08 19:44:11.084 Buzzy[1671:993557] Push Plugin register success: <cd825814 07f7757d cf9c4484 c4ca67e3 fca11d26 00e06465 ac313bd6 f8b66607>
2016-04-08 19:44:11.123 Buzzy[1671:993557] ERROR Internal navigation rejected - <allow-navigation> not set for url='about:blank'
2016-04-08 19:44:11.124 Buzzy[1671:993557] ERROR Internal navigation rejected - <allow-navigation> not set for url='about:blank'
2016-04-08 19:44:11.142 Buzzy[1671:993557] Error in Success callbackId: PushNotification183430957 : ReferenceError: Can't find variable: device
2016-04-08 19:44:11.142 Buzzy[1671:993557] Uncaught Error: ReferenceError: Can't find variable: device:314:http://localhost:12456/cordova.js
2016-04-08 19:44:13.115 Buzzy[1671:993557] Error syncing to server time:  Error: network
```
thoughts?

**Comment by adamgins** [comment]
I did try and run `raix:push-enable` too:
![screen shot 2016-04-08 at 7 57 49 pm](https://cloud.githubusercontent.com/assets/7233741/14380711/5a58fecc-fdc4-11e5-86b0-98d9423dc40c.png)

**Comment by adamgins** [comment]
@raix is there something related to this https://www.npmjs.com/package/cordova-plugin-wkwebview see:

> If you need the device plugin, use at least Cordova-iOS 3.6.3 (deviceready never fires with 3.5.0 due to a currently unknown reason).

do I need to explicitly install/load https://github.com/apache/cordova-plugin-device ?

**Comment by raix** [comment]
Awesome work @adamgins we might need to add that as a dependency or in the docs

**Comment by adamgins** [comment]
Hey just test on my test server it works... that fixed it.
I am also calling `Push.Configure` as per above, I am not sure I need that... but I got a push notification with 3.0.2 on Meteor 1.3 Yea!!! @raix thanks for help (and the package :+1: )

**Comment by raix** [comment]
Sweet man - so we should deprecate the json config and update the documentation,

**Comment by adamgins** [comment]
Not sure we should deprecate as that would be a breaking change.. or would you phase it out over time?
Also the json option did make it a bit easier to toggle between production/dev environments, it would make sense to add the flexibility into the Configure params. I guess one option could be is that you have those in Meteor Settings and you use that to swap the dev/prod in/out. Thoughts?

**Comment by raix** [comment]
@adamgins true - theres been talk about Meteor.settings in other issues - might be a good place for it. We could just add a check for `push` configuration in Meteor.settings, maybe merge public+private for the server.

**Comment by adamgins** [comment]
@raix yep, I think that would work well.

**Comment by gaboxv** [comment]
Hi @adamgins @raix I am working on android and
I have almost the same problem, I have Meteor 1.3.1 and raix:push@3.0.2, also added:
cordova:cordova-plugin-device@1.1.1 
cordova:phonegap-plugin-push@1.5.2 
manually.

I have the app hosted in a remote server, generate the APK and log in. 
O get Push: Settings userId "STX2SzQi2hsBrLREh" for app: Dgxzh8npT9RSsZNdE
But when I try to send push notifications the server tells me:
Push: Sent message "Hello" to 0 ios apps 0 android apps
Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...

It seems I am not getting the token,

Thoughts? 
Thanks!

**Comment by adamgins** [comment]
@raix mmm.. I though upgrading may fix one of my original issues... but still persisting:

```
2016-05-02 10:59:33+10:00Exception while invoking method 'raix:push-update' Error: Match error: Expected string, got object in field id
bv6r
2016-05-02 10:59:33+10:00Sanitized and reported to the client as: Match failed [400]
bv6r
2016-05-02 10:59:33+10:00 at exports.check (packages/check/match.js:34:1)
bv6r
2016-05-02 10:59:33+10:00
bv6r
2016-05-02 10:59:33+10:00 at [object Object].raixPushUpdate (packages/raix:push/lib/server/server.js:19:5)
bv6r
2016-05-02 10:59:33+10:00 at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
bv6r
2016-05-02 10:59:33+10:00 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
bv6r
2016-05-02 10:59:33+10:00 at packages/ddp-server/livedata_server.js:711:19
bv6r
2016-05-02 10:59:33+10:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
bv6r
2016-05-02 10:59:33+10:00 at packages/ddp-server/livedata_server.js:709:40
bv6r
2016-05-02 10:59:33+10:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
bv6r
2016-05-02 10:59:33+10:00 at packages/ddp-server/livedata_server.js:707:46
bv6r
2016-05-02 10:59:33+10:00 at tryCallTwo (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
bv6r
2016-05-02 10:59:33+10:00 at doResolve (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:200:13)
bv6r
2016-05-02 10:59:33+10:00 at new Promise (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:66:3)
bv6r
2016-05-02 10:59:33+10:00 at Session.method (packages/ddp-server/livedata_server.js:681:23)
bv6r
2016-05-02 10:59:33+10:00 at packages/meteorhacks_kadira/lib/hijack/wrap_session.js:52:1
bv6r
2016-05-02 10:59:33+10:00 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
bv6r
2016-05-02 10:59:33+10:00 at Session.sessionProto.protocol_handlers.method (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:51:1)
```

I know there were a bunch of other folk having issues too... any thoughts please?

**Comment by adamgins** [comment]
sorry my last comment was duplicate of https://github.com/raix/push/issues/127#issuecomment-217778170

**Comment by chrisco23** [comment]
Glad I found this thread as it seems to get me closer.

After running 'meteor add cordova:cordova-plugin-device@1.1.1', I get

`I20160511-00:28:02.938(-7) (android:http://localhost:12488/706a87c28afe2f2833e09f1faae76451d1e9bdb6.js:179) Push.Token:
I20160511-00:28:02.943(-7) (android:http://localhost:12488/706a87c28afe2f2833e09f1faae76451d1e9bdb6.js:223) Token: {"gcm":"APA91bECNHQBuGl1W0DdANTBcX3bafsxwABndUhKCl3KZGT0xWpoLOjL95GjdgkUGxPR-k9J7kFdncH3V7InSaIEOB6X6BQrJrQssM8ev5jTn7nSqidjazVMxJqvZfm033PaWO8b0LEl"}
I20160511-00:28:02.944(-7) (android:http://localhost:12488/706a87c28afe2f2833e09f1faae76451d1e9bdb6.js:179) Got token:
I20160511-00:28:16.770(-7) (android:http://localhost:12488/706a87c28afe2f2833e09f1faae76451d1e9bdb6.js:223) sending notification
I20160511-00:28:18.696(-7) (android:http://localhost:12488/706a87c28afe2f2833e09f1faae76451d1e9bdb6.js:179) Push.Notification:
I20160511-00:28:18.697(-7) (android:http://localhost:12488/706a87c28afe2f2833e09f1faae76451d1e9bdb6.js:179) Push.Message: Got message while app is open:`

Now, I am still using some Meteor.startup() code from when I first successfully used raix:push, last July(!).  I have this code from back then still:

`Meteor.startup(function () {
  console.log('inside notifications.js');
  Push.allow({
    send: function(userId, notification) {
      // Allow all users to send to everybody - For test only!
      return true;
    }
  });

  Push.debug = true;

  /* do something with push token*/
  Push.addListener('token', function(token) {
    console.log('Token: ' + JSON.stringify(token));
  });

  Push.addListener('notification', function(notification) {
    console.log('notification: ' + JSON.stringify(notification))
  });

  Push.addListener('startup', function(notification) {
    console.log('Routing Push: ' + JSON.stringify(notification));
    Router.go('warbleShow', {_id: notification.payload.warbleId});
  });
});`

In light of the messages I mentioned in that first bit of output, I tried closing the application and sending the test notification from localhost:3000 (is that even supposed to work??), and I got:

`I20160511-00:30:40.853(-7)? Push: Send message "Hello" via query {}
I20160511-00:30:40.855(-7)? Push: Sent message "Hello" to 0 ios apps 0 android apps
I20160511-00:30:40.857(-7)? Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
`

**Comment by lcfm** [comment]
Hi guys,

I have been trying and reading everything for days and days but still have no luck to solve this error :(

I have everything set and the iPhone shows a pop up asking for permission to the push notifications. However, I get the error below on xCode and I dont get any users registered. Did you find a solution?

**The error I get on xCode:**
```
2016-08-09 21:53:52.456 app[xx] Push Plugin register success: xxx
2016-08-09 21:53:52.508 app[xx] Error in Success callbackId: PushNotification176720652 : ReferenceError: Can't find variable: device
2016-08-09 21:53:52.509 app[xx] Uncaught Error: ReferenceError: Can't find variable: device:314:http://localhost:12248/cordova.js
```
**Version of packages I am using:**
```
Meteor 1.3.4.4
raix:push 3.0.2
```

Thank you very much in advance.

**Comment by lcfm** [comment]
Update:

I ran:
`meteor add cordova:cordova-plugin-device@1.1.1`

Then used the Push.Configure instead of the config.push.json and it worked! Nice!!

**Comment by raix** [comment]
`3.0.3-rc.5` should have the device dependency
