### ISSUE TITLE
Error 513 "PEM routines:PEM_read_bio:no start line"

### ISSUE THREAD

**Issue by lpender** [raix/push#163]
Hi! Wonderful work on this.

Just followed along with the terrific [iOs Micro Walkthrough](https://github.com/raix/push/wiki/iOS-Micro-Walkthrough) and got all the way to the very end without a hitch.  

However, when I try to send the final Push notification from `meteor shell` it doesn't arrive, and I see this:

```
I20151212-11:40:14.410(-5)? Push: Sent message "Congratulations" to 1 ios apps 0 android apps
I20151212-11:40:14.414(-5)? Got error code 513 for token abcdefg12345etcetcetc
W20151212-11:40:14.414(-5)? (STDERR)
W20151212-11:40:14.415(-5)? (STDERR) /Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:155
W20151212-11:40:14.415(-5)? (STDERR)                 throw e;
W20151212-11:40:14.415(-5)? (STDERR)                       ^
W20151212-11:40:14.416(-5)? (STDERR) Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
W20151212-11:40:14.416(-5)? (STDERR)     at Object.exports.createCredentials (crypto.js:129:17)
W20151212-11:40:14.416(-5)? (STDERR)     at Object.exports.connect (tls.js:1345:27)
W20151212-11:40:14.416(-5)? (STDERR)     at apnSocketLegacy (/Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/lib/socket.js:40:19)
W20151212-11:40:14.416(-5)? (STDERR)     at Connection.initialize.spread.fail.terminated (/Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/lib/con
nection.js:175:17)
W20151212-11:40:14.417(-5)? (STDERR)     at /Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:1229:26
W20151212-11:40:14.417(-5)? (STDERR)     at _fulfilled (/Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:834:54)
W20151212-11:40:14.417(-5)? (STDERR)     at self.promiseDispatch.done (/Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:863:30
)
W20151212-11:40:14.417(-5)? (STDERR)     at Promise.promise.promiseDispatch (/Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:
796:13)
W20151212-11:40:14.418(-5)? (STDERR)     at /Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:556:49
W20151212-11:40:14.418(-5)? (STDERR)     at runSingle (/Users/lpender/.meteor/packages/raix_push/.3.0.2.1qkywpz++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:137:13)
=> Exited with code: 8
```

Many thanks

**Comment by lpender** [comment]
Could this be because I haven't logged in as any user in the app?

**Comment by raix** [comment]
looks odd - I've never seen that error message. Looks as if it has troubles reading the pem files?

**Comment by lpender** [comment]
I went back and ran 

```
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert private/aps_development.pem -key private/Lee_Pender_Dev_Key.pem
```

And noticed that, although the output ends with `Verify return code: 0 (ok)`, if I scroll up to the top of the output, I see a `verify error`.

Here's the full output:

```
Enter pass phrase for LeePenderDevKey.pem:
CONNECTED(00000003)
depth=1 /C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.sandbox.push.apple.com
   i:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
 1 s:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
   i:/O=Entrust.net/OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
-----BEGIN CERTIFICATE-----
...
```

I followed the steps in this [stackoverflow post](http://stackoverflow.com/questions/23343910/verify-errornum-20-when-connecting-to-gateway-sandbox-push-apple-com) and was able to fix this by adding `-CAFile entrust_2048.cer` to the end of the command.

Does this help at all?

**Comment by raix** [comment]
we have that in the docs with a solution - can't remember where - should not cause an issue though

**Comment by woaij007** [comment]
@lpender Have you already solved this issue? I am having the same err right now.

**Comment by woaij007** [comment]
@lpender Please check if you put the cert/key file in wrong place in the configure file. It happened to me that I miss put them in the wrong place.

**Comment by yvdorofeev** [comment]
I've had the same issue - I mistakenly put a key .pem file in the "cert" setting and vice versa,.

**Comment by lpender** [comment]
That's exactly what it is. I updated the [iOs Micro Walkthrough](https://github.com/raix/push/wiki/iOS-Micro-Walkthrough) because it seemed to have them switched.

**Comment by raix** [comment]
:+1:

**Comment by ivan133** [comment]
I have exactly the same issue.
I didn't understand how do you resolve it.
Please help!

**Comment by ivan133** [comment]
Ops, I get it
I should switch
  "apn-dev": {
    "key": "apn-development/PushChatCert.pem",
    "cert": "apn-development/PushChatKey.pem"
  },
to
  "apn-dev": {
    "key": "apn-development/PushChatKey.pem",
    "cert": "apn-development/PushChatCert.pem"
  },
