### ISSUE TITLE
Socket unusable after connection. Hint: You may be using a certificate for the wrong environment

### ISSUE THREAD

**Issue by derwaldgeist** [raix/push#165]
I tried out the meteor-raix-push-demo app and updated it to Meteor 1.2 and the latest version of raix:push. Although my certificates are reported OK when testing against the APN service, I get the following error in the console each time I try to send a notification:

```
W20151213-10:27:20.357(1)? (STDERR) /Users/waldgeist/.meteor/packages/raix_push/.3.0.2.838gkc++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:155
W20151213-10:27:20.357(1)? (STDERR)                 throw e;
W20151213-10:27:20.358(1)? (STDERR)                       ^
W20151213-10:27:20.358(1)? (STDERR) Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment
W20151213-10:27:20.358(1)? (STDERR)     at Connection.connect.delay.then.fail.delay (/Users/waldgeist/.meteor/packages/raix_push/.3.0.2.838gkc++os+web.browser+web.cordova/npm/node_modules/apn/lib/connection.js:224:10)
W20151213-10:27:20.358(1)? (STDERR)     at _fulfilled (/Users/waldgeist/.meteor/packages/raix_push/.3.0.2.838gkc++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:834:54)
W20151213-10:27:20.358(1)? (STDERR)     at self.promiseDispatch.done (/Users/waldgeist/.meteor/packages/raix_push/.3.0.2.838gkc++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:863:30)
W20151213-10:27:20.358(1)? (STDERR)     at Promise.promise.promiseDispatch (/Users/waldgeist/.meteor/packages/raix_push/.3.0.2.838gkc++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:796:13)
W20151213-10:27:20.358(1)? (STDERR)     at /Users/waldgeist/.meteor/packages/raix_push/.3.0.2.838gkc++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:604:44
W20151213-10:27:20.359(1)? (STDERR)     at runSingle (/Users/waldgeist/.meteor/packages/raix_push/.3.0.2.838gkc++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:137:13)
W20151213-10:27:20.359(1)? (STDERR)     at flush (/Users/waldgeist/.meteor/packages/raix_push/.3.0.2.838gkc++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:125:13)
W20151213-10:27:20.359(1)? (STDERR)     at process._tickCallback (node.js:448:13)
=> Exited with code: 8
W20151213-10:27:24.355(1)? (STDERR) WARNING: Push APN is using development key and certificate
```

After reading #134, I also explicitly set the NODE_ENV variable to "development" (which wasn't present before), but this did not change anything. I am testing on a localhost, and in the json the production flag is set to false, so it should take the development cert and key.

**Comment by derwaldgeist** [comment]
My fault. I used the apn-dev key instead of apn and vice-versa.

**Comment by Mani-87** [comment]
getting below error my certificate validate upto september 2022 on production mode

Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment
    at Connection.<anonymous> (/home/gettaskrabbit/tdemo/node_modules/apn/lib/connection.js:259:10)
    at _fulfilled (/home/gettaskrabbit/tdemo/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/gettaskrabbit/tdemo/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/gettaskrabbit/tdemo/node_modules/q/q.js:796:13)
    at /home/gettaskrabbit/tdemo/node_modules/q/q.js:604:44
    at runSingle (/home/gettaskrabbit/tdemo/node_modules/q/q.js:137:13)
    at flush (/home/gettaskrabbit/tdemo/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
kindly suggest someone to fix this

**Comment by jatinshrivastava** [comment]
@derwaldgeist  how did u generate the pem file for key and certificate?
Can you share the commands? 
I tried the commands mentioned in: https://github.com/raix/push/blob/v3.x/docs/IOS.md but still I am getting this same error.
Thanks in advance. :)

**Comment by paulo-ridery** [comment]
@jatinshrivastava did you solve it? I am getting the same error

**Comment by sunhaolin** [comment]
the same error:
```bash
2025-04-29T05:44:44.306088610Z Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment
2025-04-29T05:44:44.306127609Z     at Connection.<anonymous> (/app/node_modules/apn/lib/connection.js:224:10)
2025-04-29T05:44:44.306134174Z     at _fulfilled (/app/node_modules/q/q.js:854:54)
2025-04-29T05:44:44.306139195Z     at /app/node_modules/q/q.js:883:30
2025-04-29T05:44:44.306144059Z     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:816:13)
2025-04-29T05:44:44.306149004Z     at /app/node_modules/q/q.js:624:44
2025-04-29T05:44:44.306166994Z     at runSingle (/app/node_modules/q/q.js:137:13)
2025-04-29T05:44:44.306171961Z     at flush (/app/node_modules/q/q.js:125:13)
2025-04-29T05:44:44.306176801Z     at processTicksAndRejections (internal/process/task_queues.js:77:11)
2025-04-29T05:44:44.416354550Z error Command failed with exit code 1.
```
