### ISSUE TITLE
[Meteor 1.3-beta.12] (Cross-Post-Issue) Error building with raix:push - Package configured via .json config file

### ISSUE THREAD

**Issue by DanielDornhardt** [raix/push#185]
Hello, i've posted the following error to the Meteor Issue Tracker already, see link below.

The thing is, I think it's possible to configure raix:push without the .json - File, which would be a workaround, but I don't get exactly how to configure the client side. The docs lead to the recommendation to use the configuration of the cordova push package: https://github.com/raix/push/blob/v3.x/docs/ADVANCED.md#note-outdated , but the supplied link https://github.com/phonegap/phonegap-plugin-push#pushnotificationinitoptions doesn't seem to lead to an explanation of the config anymore.

Maybe somebody can give a hands-on example of how to deal with it?

Or maybe it's possible to move this to Meteor.settings or upgrade the Push.Configure - call to set the required parameters for phonegap-plugin-push?

This is the error I posted:

Link: https://github.com/meteor/meteor/issues/6411

Text:

---

I receive this of error since updating from 1.3 Beta 11 to 1.3 Beta 12:

    Error: sourcePath not a file: push.config.web.browser.js
        at ImportScanner._ensureSourcePath (/tools/isobuild/import-scanner.js:208:13)
        at /tools/isobuild/import-scanner.js:101:28
        at Array.forEach (native)
        at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:100:11)
        at /tools/isobuild/compiler-plugin.js:709:15
        at Array.forEach (native)
        at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:689:19)
        at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
        at /tools/isobuild/bundler.js:516:12
        at /tools/utils/buildmessage.js:359:18
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:352:34
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:350:23
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at Object.enterJob (/tools/utils/buildmessage.js:324:26)
        at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
        at /tools/isobuild/bundler.js:2232:14
        at /tools/isobuild/bundler.js:2322:20
        at Array.forEach (native)
        at Function._.each._.forEach (/Users/spaceman/.meteor/packages/meteor-tool/.1.1.13-beta.12.1p7kgab++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
        at /tools/isobuild/bundler.js:2321:7
        at /tools/utils/buildmessage.js:271:13
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:264:29
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:262:18
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:253:23
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at Object.capture (/tools/utils/buildmessage.js:252:19)
        at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
        at /tools/runners/run-app.js:586:36
        at Function.run (/tools/tool-env/profile.js:489:12)
        at bundleApp (/tools/runners/run-app.js:576:34)
        at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
        at AppRunner._fiber (/tools/runners/run-app.js:881:28)
        at /tools/runners/run-app.js:406:12

After a lot of humming and hawing, it seems to boil down to this:

raix:push is structured to be configured using a file `config.push.json` in the meteor projects' root directory.

Then there seems to be some kind of build plugin which is supposed to read the file and actually add some additional javascript. The whole thing is registered here: https://github.com/raix/push/blob/f3a5a653dc2d1d7cd1af0b4d6478d23bcbd0644f/plugin/push.configuration.js#L185

...AAAND that's how far I can isolate the error. Something (a lot I feel?) changed in the build process from 1.3 Beta 11 to 1.3 Beta 12 and this is one issue which probably needs to be patched somewhere.

Reproduction Repo: https://github.com/DanielDornhardt/meteor13Beta12errorBuildingWithRaixPushPackage

- just remove or rename the file config.push.json to see the build error disappear.

**Comment by skirunman** [comment]
We have the same issue. Would be awesome if Meteor could resolve this ASAP.

**Comment by raix** [comment]
I havent gone into depth but could this be just an issue with the json configuration?

**Comment by DanielDornhardt** [comment]
Hello @raix , I don't think so. Please take a look at the [config.push.json-file in the reproduction repo](https://github.com/DanielDornhardt/meteor13Beta12errorBuildingWithRaixPushPackage/blob/master/config.push.json) - it's the same file we're using in our app, except the keys and filenames have been changed.

The values - and the file - was always working for us with meteor versions < 1.3 .

**Comment by raix** [comment]
We might want to replace the `json` config way of doing it in favor of using the import/export pattern eg. allowing:

`push.config.client.js`
```js
export default {
  "gcm": {
    "projectNumber": 11111111111111
  },
  "production": false,
  "badge": true,
  "sound": true,
  "alert": true,
  "vibrate": true,
  "iconColor": "#FFFFFF"
};
```

`push.config.server.js`
```js
import clientConfig from './push.config.client.js';
export default Object.assign({ // xxx: this extend might not be 100% correct...
  "apn-dev": {
    "passphrase": "test",
    "key": "example.pem",
    "cert": "example2.pem"
  },
  "apn": {
    "passphrase": "test",
    "key": "example.pem",
    "cert": "example2.pem"
  },
  "gcm": {
    "apiKey": "00000000000000000000000000000",
  }
}, clientConfig);
```

`app.client.js`
```js
  import clientConfig from './push.config.client.js';
  Push.Configuration(clientConfig);
```

`app.server.js`
```js
  import serverConfig from './push.config.server.js';
  Push.Configuration(serverConfig);
```

**Comment by DanielDornhardt** [comment]
Hello, thank you for the example code, that gives us something to work with.

I actually didn't get why you used the .json - file in the first case instead of the Meteor.settings - is it because you wanted to prevent the keys of every platform to "leak" to every client?

Are you trying to package the key and cert files for each platform only for the builds of that specific platform?

**Comment by raix** [comment]
the nice thing about the json config is that all configuration can be done in one place - the package will compile it into a client and a server configuration. (should not leak server keys etc.)

Having said that using Push.Configuration directly might be the way to go in larger setups making it possible to have the push send server as a separate microservice

**Comment by DanielDornhardt** [comment]
Hi,

not leaking Server Keys could also be done by using the /private/ meteor special directory and / or the non-public keys of the settings mechanism, right?

Or maybe even let users provide a path to a file somewhere, and one possible delivery mechanism would be the /private/ directory, which gets included in the build for the server?

I don't know how you read the files, you probably depend on some other package to read the files, but I think that might be good meteor-compatible options?

**Comment by raix** [comment]
private is for the cert/key but true have the files in separate client/server folders would do the trick too

**Comment by DanielDornhardt** [comment]
Btw, this seems to have been fixed / worked around in Meteor and might be good again in the next Meteor 1.3 Beta: https://github.com/meteor/meteor/issues/6411

**Comment by raix** [comment]
Thanks @DanielDornhardt good to know

**Comment by MichaelJCole** [comment]
Hey, I'd also be excited about having these settings in settings.json.  I already have a system setup to manage dev/stage/prod settings via settings.json, and this extra config is extra work.

**Comment by skirunman** [comment]
Agreed that having keys in settings.json would be ideal.
