### ISSUE TITLE
 Exception while invoking method 'serverNotification' ReferenceError: result is not defined

### ISSUE THREAD

**Issue by Wade-BuildOtto** [raix/push#198]
When I call this function it looks like its not getting passed a result, not really sure how this works just yet.

**Comment by Wade-BuildOtto** [comment]
I feel like its the last mile, and this is the only thing holding it up. any help would really be appreciated. 
What is result and where does it come from. 

Exception while invoking method 'serverNotification' ReferenceError: result is not defined
    at [object Object].Meteor.methods.serverNotification (server/pushMethods.js:22:30)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/mnt/app/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/mnt/app/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
    at new Promise (/mnt/app/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)

**Comment by Wade-BuildOtto** [comment]
if any one has any ideas please let me know, I could really use some help with this one.

**Comment by Wade-BuildOtto** [comment]
Just to note, I am running this on Modulus and I am getting a app Id, and I have verified my Dev Certificate, plus I am testing it on the server not local host.

**Comment by bryanterrell** [comment]
@Wade-BuildOtto - I'm guessing you might be using the example from http://stached.io/standalone/fBLmRhsAuPSxKBSgM, which has a result variable that isn't defined. If that's the case try removing the lines with ` historyId: result`.

**Comment by Wade-BuildOtto** [comment]
I removed the HistoryId from both server notification and user notification methods, the messages are now writing and trying to sent out, but I am getting a new error. 

Push: Send message "test" via query {}

Exception in setInterval callback: ReferenceError: EJSON is not defined
    at EventEmitter.self.sendAPN (packages/raix_push/packages/raix_push.js:311:1)
    at packages/raix_push/packages/raix_push.js:481:1
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:869:1)
    at _querySend (packages/raix_push/packages/raix_push.js:474:1)
    at EventEmitter.self.serverSend (packages/raix_push/packages/raix_push.js:580:1)
    at packages/raix_push/packages/raix_push.js:659:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)

**Comment by Wade-BuildOtto** [comment]
I removed the HistoryId from both server notification and user notification
methods, the messages are now writing and trying to sent out, but I am
getting a new error.

Push: Send message "test" via query {}

Exception in setInterval callback: ReferenceError: EJSON is not defined
    at EventEmitter.self.sendAPN
(packages/raix_push/packages/raix_push.js:311:1)
    at packages/raix_push/packages/raix_push.js:481:1
    at [object Object]._.extend.forEach
(packages/mongo/mongo_driver.js:1022:1)
    at [object Object].Cursor.(anonymous function) [as forEach]
(packages/mongo/mongo_driver.js:869:1)
    at _querySend (packages/raix_push/packages/raix_push.js:474:1)
    at EventEmitter.self.serverSend
(packages/raix_push/packages/raix_push.js:580:1)
    at packages/raix_push/packages/raix_push.js:659:1
    at [object Object]._.extend.withValue
(packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)

**Comment by Wade-BuildOtto** [comment]
installed meteor ejson which is now in the dependencies as well, and it works fine.
