### ISSUE TITLE
APN connection timeout

### ISSUE THREAD

**Issue by MaxShv** [raix/push#200]
We are getting the following issue in production. Is it possible to update to the newer version of node-apn? It seems like it was fixed in version 1.7.2.

```
Connect timed out stack:Error: Connect timed out
at Connection. (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

**Comment by Alveoli** [comment]
+1

Same problem here on production.  If I reboot servers and send the same notification, it succeeds.

What do you think is the cause?  Because mine works again, I can't believe it's an out of date certificate.  I'm suspecting it's a volume problem (I('m sending to thousands of named devices).  Would be great to have your thoughts on the matter, so a workaround can be created.

**Comment by raix** [comment]
Make sure the needed ports are open on the network

**Comment by Alveoli** [comment]
Hi! Yep, ports are open.

In my case I was pushing tens of thousands of notifications via a single call to `Push.send({query:{}})`.  That seemed to have fouled something up.

I've worked around it by putting far fewer pushes through each `Push.send` call and using sendInterval and sendBatchSize to control push speed.

**Comment by raix** [comment]
ah gotcha @Alveoli - It might be helpful for others if we could improve docs on that

**Comment by pozylon** [comment]
+1

Crashed my server this morning.

`crossiety-one        | Error: Connect timed out
crossiety-one        |     at Connection.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
crossiety-one        |     at Timer.listOnTimeout (timers.js:92:15)
`

https://github.com/raix/push/issues/229
