### ISSUE TITLE
Exception in setInterval callback: ReferenceError: EJSON is not defined

### ISSUE THREAD

**Issue by Wade-BuildOtto** [raix/push#208]
Push: Send message "test" via query {}

send to token { apn: '....' }

Exception in setInterval callback: ReferenceError: EJSON is not defined
    at EventEmitter.self.sendAPN (packages/raix_push/packages/raix_push.js:311:1)
    at packages/raix_push/packages/raix_push.js:481:1
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:869:1)
    at _querySend (packages/raix_push/packages/raix_push.js:474:1)
    at EventEmitter.self.serverSend (packages/raix_push/packages/raix_push.js:580:1)
    at packages/raix_push/packages/raix_push.js:659:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)

**Comment by Wade-BuildOtto** [comment]
Meteor add ejson resolved it, apparently there are dependancies

**Comment by raix** [comment]
Is this still an issue?

There should be a ref in 3.0.0 versions https://github.com/raix/push/blob/fix-device-dependency-deprecate-json-format/package.js#L52

**Comment by Wade-BuildOtto** [comment]
once I installed it, it worked fine, Thx.
