### ISSUE TITLE
token: {unknown: '...'}

### ISSUE THREAD

**Issue by philipthomasme** [raix/push#217]
I don't know when this changed but currently I am not able to get the correct token.
Instead of saying
`token: {apn: '...'}`
it says
`token: {unknown: '...'}`

Complete error message:

> Push: Got push token from app: { id: '...',
token: { unknown: '...' },
appName: 'main',
userId: null,
metadata: {} }
Exception while invoking method 'raix:push-update' Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation in field token
at exports.check (packages/check/match.js:34:1)
at [object Object].raixPushUpdate (packages/raix:push/lib/server/server.js:19:5)
 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
at packages/ddp-server/livedata_server.js:711:19
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at packages/ddp-server/livedata_server.js:709:40
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at packages/ddp-server/livedata_server.js:707:46
at tryCallTwo (/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
at doResolve (/bundle/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:200:13)
Sanitized and reported to the client as: Match failed [400]

userId: null is correct because I use raix:push without user registration.

I did not check for Android yet.

Running
- Meteor 1.3.2.4
- raix:push 3.0.2
- cordova-plugin-device 1.1.1

Thanks in advance for any help!

**Comment by philipthomasme** [comment]
Sorry, was a problem in my app itself.
No problem with the plugin.
