### ISSUE TITLE
getting error when I send push notifications from production (Error: error:0906D06C:PEM routines:PEM_read_bio:no start line)

### ISSUE THREAD

**Issue by adim86** [raix/push#277]
Hi,

Everytime I send a push notification on production I get this error in the logs and I am not sure what is causing it, any help will be appreciated

/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:155
                throw e;
[xxx.xxx.xxx.xxx](ip address)                       ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.exports.createCredentials (crypto.js:126:17)
    at Object.exports.connect (tls.js:1345:27)
    at apnSocketLegacy (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/socket.js:40:19)
    at Connection.initialize.spread.fail.terminated (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:175:17)
    at /bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:1229:26
    at _fulfilled (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:796:13)
    at /bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:556:49
    at runSingle (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/bundle/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:458:13)

**Comment by visidoo** [comment]
We are facing the same issue. Any progress with this problem? Any help is apprecciated, too ;)

**Comment by adim86** [comment]
For some reason, my Apple certificates used in the push notifications were deleted so I made new ones and set it up again. The problem went away
