### ISSUE TITLE
apn/node_modules/q/q.js

### ISSUE THREAD

**Issue by yuwanlin** [raix/push#289]
raix:push@3.1.0-pre.1

when I build a app with the development environment, And send a notification(Meteor.call('serverNotification', 'xx', 'xx') from browser console). But the terminal give me a exception.

```
W20170405-16:32:10.133(8)? (STDERR) /Users/ioobot/.meteor/packages/raix_push/.3.0.2.zh81jy++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:155
W20170405-16:32:10.134(8)? (STDERR)                 throw e;
W20170405-16:32:10.134(8)? (STDERR)                 ^
W20170405-16:32:10.134(8)? (STDERR) 
W20170405-16:32:10.135(8)? (STDERR) Error: Connect timed out
W20170405-16:32:10.135(8)? (STDERR)     at Connection.<anonymous> (/Users/ioobot/.meteor/packages/raix_push/.3.0.2.zh81jy++os+web.browser+web.cordova/npm/node_modules/apn/lib/connection.js:193:36)
W20170405-16:32:10.136(8)? (STDERR)     at Timer.listOnTimeout (timers.js:92:15)
=> Exited with code: 1
W20170405-16:32:18.537(8)? (STDERR) WARNING: Push APN is using development key and certificate

```

what's wrong with q.js ?

**Comment by raix** [comment]
It might be that you need to open additional ports on your network when connecting to apple.
