### ISSUE TITLE
Error: Unknown asset: private/apnDevKey.pem

### ISSUE THREAD

**Issue by mvaisanen** [raix/push#31]
I get an error when I try to run meteor.
`Error: Unknown asset: private/apnDevKey.pem`

I have double-checked about million times the file names and path.

**config.push.json**
```
{
  "apn": {
    "passphrase": "devdev",
    "key": "private/apnDevKey.pem",
    "cert": "private/apnDevCert.pem", 
    "gateway": "gateway.sandbox.push.apple.com"
  },
  "production": false
}
```
![My folder structure.](https://cloud.githubusercontent.com/assets/7551056/5820670/33efbcba-a0cf-11e4-8c4d-8ae8bc5b5659.png)

**Repo**
https://github.com/mvaisanen/SimplePushApp

**The full terminal output:**
```
$ meteor
[[[[[ ~/Devaus/meteor/myapp ]]]]]             

=> Started proxy.                             
=> Started MongoDB.                           
W20150120-18:08:59.792(2)? (STDERR)           
W20150120-18:08:59.899(2)? (STDERR) /Users/Mika/.meteor/packages/meteor-tool/.1.0.38.zbazwc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150120-18:08:59.899(2)? (STDERR) 						throw(ex);
W20150120-18:08:59.900(2)? (STDERR) 						      ^
W20150120-18:08:59.900(2)? (STDERR) Error: Unknown asset: private/apnDevKey.pem
W20150120-18:08:59.900(2)? (STDERR)     at Object.Future.wait (/Users/Mika/.meteor/packages/meteor-tool/.1.0.38.zbazwc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:323:16)
W20150120-18:08:59.900(2)? (STDERR)     at getAsset (/Users/Mika/Devaus/meteor/myapp/.meteor/local/build/programs/server/boot.js:150:20)
W20150120-18:08:59.900(2)? (STDERR)     at Object.Assets.getText (/Users/Mika/Devaus/meteor/myapp/.meteor/local/build/programs/server/boot.js:155:16)
W20150120-18:08:59.901(2)? (STDERR)     at app/push.config.os.js:3:21
W20150120-18:08:59.901(2)? (STDERR)     at app/push.config.os.js:10:3
W20150120-18:08:59.901(2)? (STDERR)     at /Users/Mika/Devaus/meteor/myapp/.meteor/local/build/programs/server/boot.js:175:10
W20150120-18:08:59.901(2)? (STDERR)     at Array.forEach (native)
W20150120-18:08:59.901(2)? (STDERR)     at Function._.each._.forEach (/Users/Mika/.meteor/packages/meteor-tool/.1.0.38.zbazwc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150120-18:08:59.902(2)? (STDERR)     at /Users/Mika/Devaus/meteor/myapp/.meteor/local/build/programs/server/boot.js:86:5
W20150120-18:08:59.902(2)? (STDERR)     - - - - -
W20150120-18:08:59.902(2)? (STDERR)     at getAsset (/Users/Mika/Devaus/meteor/myapp/.meteor/local/build/programs/server/boot.js:144:19)
W20150120-18:08:59.902(2)? (STDERR)     at Object.Assets.getText (/Users/Mika/Devaus/meteor/myapp/.meteor/local/build/programs/server/boot.js:155:16)
W20150120-18:08:59.903(2)? (STDERR)     at app/push.config.os.js:3:21
W20150120-18:08:59.903(2)? (STDERR)     at app/push.config.os.js:10:3
W20150120-18:08:59.903(2)? (STDERR)     at /Users/Mika/Devaus/meteor/myapp/.meteor/local/build/programs/server/boot.js:175:10
W20150120-18:08:59.904(2)? (STDERR)     at Array.forEach (native)
W20150120-18:08:59.904(2)? (STDERR)     at Function._.each._.forEach (/Users/Mika/.meteor/packages/meteor-tool/.1.0.38.zbazwc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150120-18:08:59.905(2)? (STDERR)     at /Users/Mika/Devaus/meteor/myapp/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
```

**Comment by mvaisanen** [comment]
Got it. Asset path is relative to the "private" directory
