### ISSUE TITLE
Error: socket hang up (my certificate is not expired!)

### ISSUE THREAD

**Issue by lcfm** [raix/push#351]
Hi guys,

I've been using this package for maybe one year and a half and has worked just fine.

In january I renewed my push certificate from Apple, updated my app and it was just working fine.

This week I started having the error below out of the blue, with no new deploy and no different activity in the app. Now every time it tries to send a push the app crashes.

Does anyone have any idea what can be? I was not able to find the cause.

Thank you very much

```
2018-10-01T22:41:46.631811+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:155
2018-10-01T22:41:46.631855+00:00 app[web.1]: throw e;
2018-10-01T22:41:46.631857+00:00 app[web.1]: ^
2018-10-01T22:41:46.631859+00:00 app[web.1]: 
2018-10-01T22:41:46.631861+00:00 app[web.1]: Error: socket hang up
2018-10-01T22:41:46.631864+00:00 app[web.1]: at TLSSocket.onHangUp (_tls_wrap.js:1095:19)
2018-10-01T22:41:46.631866+00:00 app[web.1]: at TLSSocket.g (events.js:260:16)
2018-10-01T22:41:46.631868+00:00 app[web.1]: at emitNone (events.js:72:20)
2018-10-01T22:41:46.631869+00:00 app[web.1]: at TLSSocket.emit (events.js:166:7)
2018-10-01T22:41:46.631871+00:00 app[web.1]: at endReadableNT (_stream_readable.js:923:12)
2018-10-01T22:41:46.631873+00:00 app[web.1]: at nextTickCallbackWith2Args (node.js:511:9)
2018-10-01T22:41:46.631875+00:00 app[web.1]: at process._tickCallback (node.js:425:17)
```
In the end it also shows (some data replaced for dummy):

```
2018-10-01T22:41:46.363398+00:00 app[web.1]: Push: Sent message "John Doe liked your review!" to 45 ios apps 3 android apps
2018-10-01T22:41:46.444563+00:00 app[web.1]: ANDROID: Result of sender: {"multicast_id":someid,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"someid"}]}
2018-10-01T22:41:46.447219+00:00 app[web.1]: ANDROID: Result of sender: {"multicast_id":someid,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"someid"}]}
2018-10-01T22:41:46.448085+00:00 app[web.1]: ANDROID: Result of sender: {"multicast_id":someid,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"someid"}]}

```

And shows the crash:

```
2018-10-01T22:41:46.775723+00:00 heroku[web.1]: State changed from up to crashed
2018-10-01T22:41:46.755603+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by adamgins** [comment]
@lcfm did you solve this?

**Comment by lcfm** [comment]
Very unforunately I did not :(

Actually I had to abandon the package and abandon push notifications in my app because of this issue, quite frustrating.

**Comment by shivang007** [comment]
@lcfm This seems to be error in apn's npm module. Anyways we are moving from apn/gcm to fcm, hence this might be resolved in the next release.
