### ISSUE TITLE
Error when i starting the demo app

### ISSUE THREAD

**Issue by giggioz** [raix/push#40]
I have a long error message on my console when i run the meteor command to start the demo app meteor-raix-push-demo but i'm sure that these errors come from the raix:push package (because i tried to add the package to a new meteor project), any idea?

Thanks

giggioz@MacGiggioz:~/Spaghetti/meteor-raix-push-demo$ meteor
[[[[[ ~/Spaghetti/meteor-raix-push-demo ]]]]]

=> Started proxy.

=> A patch (Meteor 1.0.3.2) for your current release is available!
Update this project now with 'meteor update --patch'.
Push configuration, Error: Unexpected token / SyntaxError: Unexpected token /
at Object.parse (native)
at Package (packages/configuration/plugin/push.configuration.js:147:1)
at bottom_mark (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/parse-stack.js:92:14)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:739:43
at Array.forEach (native)
at Function..each..forEach (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
at compileUnibuild (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:325:5)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:135:26
at Array.forEach (native)
at Function..each..forEach (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
at Object.compiler.compile (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:131:5)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:2023:24
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:264:13
at [object Object]..extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:257:29
at [object Object]..extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:255:18
at [object Object]..extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:246:23
at [object Object]..extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
at Object.capture (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:245:19)
at Object.exports.bundle (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1975:31)
at bundleApp (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:508:34)
at [object Object]..extend._runOnce (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:544:35)
at [object Object]..extend.fiber (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:771:28)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:366:12
Push configuration, Error: Unexpected token / SyntaxError: Unexpected token /
at Object.parse (native)
at Package (packages/configuration/plugin/push.configuration.js:147:1)
at __bottom_mark_ (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/parse-stack.js:92:14)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:739:43
at Array.forEach (native)
at Function..each..forEach (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
at compileUnibuild (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:325:5)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:135:26
at Array.forEach (native)
at Function..each..forEach (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
at Object.compiler.compile (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:131:5)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:2023:24
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:264:13
at [object Object]..extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:257:29
at [object Object]..extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:255:18
at [object Object]..extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:246:23
at [object Object]..extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
at Object.capture (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:245:19)
at Object.exports.bundle (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1975:31)
at bundleApp (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:508:34)
at [object Object]..extend._runOnce (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:544:35)
at [object Object]..extend._fiber (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:771:28)
at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:366:12

**Comment by raix** [comment]
Cant have comments in json config

**Comment by giggioz** [comment]
I feel dumb but...ehy! Thanks a lot.

**Comment by raix** [comment]
no prob. I might add better config support later on - perhaps Meteor will create a pattern for it - maybe just use the Meteor settings config.
