### ISSUE TITLE
Issue adding plugin on Cordova 5.1.1

### ISSUE THREAD

**Issue by encke** [raix/push#83]
I have an error adding the plugin on Cordova 5.1.1
$ cordova plugin add https://github.com/phonegap-build/PushPlugin.git
Fetching plugin "https://github.com/phonegap-build/PushPlugin.git" via git clone
Repository "https://github.com/phonegap-build/PushPlugin.git" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted '/var/folders/8h/n9m0s_2x5mxby9qy8kvyz3kr0000gp/T/git/1435359586765/Example'
    at Object.fs.renameSync (fs.js:554:18)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44

**Comment by Tim-W** [comment]
I don't think Meteor officially supports Cordova 5 yet? It could be an issue in meteor core instead of in this package.

**Comment by raix** [comment]
Please try `raix:push@3.0.0-rc.2`
